/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'refundAmount' : IDL.Opt(IDL.Nat),
  'status' : BookingStatus,
  'endDate' : IDL.Text,
  'platformFee' : IDL.Nat,
  'hallPriceTotal' : IDL.Nat,
  'cancellationReason' : IDL.Opt(IDL.Text),
  'guestCount' : IDL.Nat,
  'createdAt' : Time,
  'hallOwnerId' : IDL.Principal,
  'totalDays' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'updatedAt' : Time,
  'customerId' : IDL.Principal,
  'stripePaymentIntentId' : IDL.Text,
  'hallId' : IDL.Text,
  'startDate' : IDL.Text,
  'eventType' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Facility = IDL.Variant({
  'ac' : IDL.Null,
  'wifi' : IDL.Null,
  'restrooms' : IDL.Null,
  'stage' : IDL.Null,
  'projector' : IDL.Null,
  'soundSystem' : IDL.Null,
  'catering' : IDL.Null,
  'parking' : IDL.Null,
});
export const Hall = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Nat,
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'facilities' : IDL.Vec(Facility),
  'capacity' : IDL.Nat,
  'contactPhone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'bookingId' : IDL.Text,
  'createdAt' : Time,
  'comment' : IDL.Text,
  'customerId' : IDL.Principal,
  'hallId' : IDL.Text,
  'rating' : IDL.Nat,
});
export const BookedDateRange = IDL.Record({
  'endDate' : IDL.Text,
  'startDate' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PlatformStats = IDL.Record({
  'totalHalls' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'confirmBookingPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createBooking' : IDL.Func([Booking], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createHall' : IDL.Func([Hall], [], []),
  'createReview' : IDL.Func([Review], [], []),
  'deleteHall' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllHalls' : IDL.Func([], [IDL.Vec(Hall)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getBookedDates' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookedDateRange)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHall' : IDL.Func([IDL.Text], [Hall], ['query']),
  'getHallReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyHallBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyHalls' : IDL.Func([], [IDL.Vec(Hall)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getReview' : IDL.Func([IDL.Text], [Review], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markBookingCompleted' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateHall' : IDL.Func([Hall], [], []),
  'updateReview' : IDL.Func([Review], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'refundAmount' : IDL.Opt(IDL.Nat),
    'status' : BookingStatus,
    'endDate' : IDL.Text,
    'platformFee' : IDL.Nat,
    'hallPriceTotal' : IDL.Nat,
    'cancellationReason' : IDL.Opt(IDL.Text),
    'guestCount' : IDL.Nat,
    'createdAt' : Time,
    'hallOwnerId' : IDL.Principal,
    'totalDays' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'updatedAt' : Time,
    'customerId' : IDL.Principal,
    'stripePaymentIntentId' : IDL.Text,
    'hallId' : IDL.Text,
    'startDate' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Facility = IDL.Variant({
    'ac' : IDL.Null,
    'wifi' : IDL.Null,
    'restrooms' : IDL.Null,
    'stage' : IDL.Null,
    'projector' : IDL.Null,
    'soundSystem' : IDL.Null,
    'catering' : IDL.Null,
    'parking' : IDL.Null,
  });
  const Hall = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Nat,
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'facilities' : IDL.Vec(Facility),
    'capacity' : IDL.Nat,
    'contactPhone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'bookingId' : IDL.Text,
    'createdAt' : Time,
    'comment' : IDL.Text,
    'customerId' : IDL.Principal,
    'hallId' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const BookedDateRange = IDL.Record({
    'endDate' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PlatformStats = IDL.Record({
    'totalHalls' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'confirmBookingPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createBooking' : IDL.Func([Booking], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createHall' : IDL.Func([Hall], [], []),
    'createReview' : IDL.Func([Review], [], []),
    'deleteHall' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllHalls' : IDL.Func([], [IDL.Vec(Hall)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getBookedDates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookedDateRange)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHall' : IDL.Func([IDL.Text], [Hall], ['query']),
    'getHallReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyHallBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyHalls' : IDL.Func([], [IDL.Vec(Hall)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getReview' : IDL.Func([IDL.Text], [Review], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markBookingCompleted' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateHall' : IDL.Func([Hall], [], []),
    'updateReview' : IDL.Func([Review], [], []),
  });
};

export const init = ({ IDL }) => { return []; };