/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookedDateRange { 'endDate' : string, 'startDate' : string }
export interface Booking {
  'id' : string,
  'refundAmount' : [] | [bigint],
  'status' : BookingStatus,
  'endDate' : string,
  'platformFee' : bigint,
  'hallPriceTotal' : bigint,
  'cancellationReason' : [] | [string],
  'guestCount' : bigint,
  'createdAt' : Time,
  'hallOwnerId' : Principal,
  'totalDays' : bigint,
  'grandTotal' : bigint,
  'updatedAt' : Time,
  'customerId' : Principal,
  'stripePaymentIntentId' : string,
  'hallId' : string,
  'startDate' : string,
  'eventType' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type Facility = { 'ac' : null } |
  { 'wifi' : null } |
  { 'restrooms' : null } |
  { 'stage' : null } |
  { 'projector' : null } |
  { 'soundSystem' : null } |
  { 'catering' : null } |
  { 'parking' : null };
export interface Hall {
  'id' : string,
  'owner' : Principal,
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'size' : bigint,
  'description' : string,
  'photoIds' : Array<string>,
  'isActive' : boolean,
  'pricePerDay' : bigint,
  'address' : string,
  'contactEmail' : string,
  'facilities' : Array<Facility>,
  'capacity' : bigint,
  'contactPhone' : string,
}
export interface PlatformStats {
  'totalHalls' : bigint,
  'totalBookings' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
}
export interface Review {
  'id' : string,
  'bookingId' : string,
  'createdAt' : Time,
  'comment' : string,
  'customerId' : Principal,
  'hallId' : string,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[string, string, bigint], undefined>,
  'confirmBookingPayment' : ActorMethod<[string, string], undefined>,
  'createBooking' : ActorMethod<[Booking], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createHall' : ActorMethod<[Hall], undefined>,
  'createReview' : ActorMethod<[Review], undefined>,
  'deleteHall' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllHalls' : ActorMethod<[], Array<Hall>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getBookedDates' : ActorMethod<[string], Array<BookedDateRange>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHall' : ActorMethod<[string], Hall>,
  'getHallReviews' : ActorMethod<[string], Array<Review>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyHallBookings' : ActorMethod<[], Array<Booking>>,
  'getMyHalls' : ActorMethod<[], Array<Hall>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getReview' : ActorMethod<[string], Review>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markBookingCompleted' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateHall' : ActorMethod<[Hall], undefined>,
  'updateReview' : ActorMethod<[Review], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];